config/routes.rb
Crossingmusic::Application.routes.draw do |map|
  match "/album/:album_id/delete_song/:id" => "songs#destroy",:as=>:delete_song
  resources :albums do
    resources :songs
  end
  

  resources :users,:all_song_charts,:contact_messages
  
  resources :user_sessions

  match "/", :to => "albums#index"
  match "/about", :to => "main#about"
  match "/contact", :to => "main#contact",:as=>:contact_us
  match "login" => "user_sessions#new",:as=>:login
  match "logout" => "user_sessions#destroy",:as=>:logout
  match "/song_votes/reset" => "song_votes#reset",:as=>:reset_votes

  match ':controller(/:action(/:id(.:format)))'
end

app/models/song_vote.rb
class SongVote < ActiveRecord::Base
  belongs_to :song
  
  scope :positive, where(:vote=>"YES")
  scope :negative, where(:vote=>"NO")
  scope :neutral, where(:vote=>"MEH")
  
  validates :vote,   :presence=>true
  validates :song_id,:presence=>true
  
  def self.chart_data
    data = {:positive=>[],:neutral=>[],:negative=>[]}
    Song.ordered.each do |song|
      data[:positive] << song.song_votes.positive.size
      data[:neutral] << song.song_votes.neutral.size
      data[:negative] << song.song_votes.negative.size
    end
    "[{name: 'Positive',data: [#{data[:positive] * ","}]},{name: 'Neutral',data: [#{data[:neutral] * ","}]},{name: 'Negative',data: [#{data[:negative] * ","}]}]"
  end
end

app/controllers/song_votes_controller.rb
class SongVotesController < ApplicationController
  before_filter do
    @tab = "SONGS"
  end
  # GET /song_votes
  # GET /song_votes.xml
  def index
    @song_votes = SongVote.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @song_votes }
    end
  end

  # GET /song_votes/1
  # GET /song_votes/1.xml
  def show
    @song_vote = SongVote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @song_vote }
    end
  end

  # GET /song_votes/new
  # GET /song_votes/new.xml
  def new
    @song_vote = SongVote.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @song_vote }
    end
  end

  # GET /song_votes/1/edit
  def edit
    @song_vote = SongVote.find(params[:id])
  end

  # POST /song_votes
  # POST /song_votes.xml
  def create
    @song = Song.find(params[:song_id])
    @song_vote = SongVote.new(params[:song_vote])

    respond_to do |format|
      if @song_vote.save
        format.html { redirect_to(@song.next || songs_path) }
        format.xml  { render :xml => @song_vote, :status => :created, :location => @song_vote }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @song_vote.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /song_votes/1
  # PUT /song_votes/1.xml
  def update
    @song_vote = SongVote.find(params[:id])

    respond_to do |format|
      if @song_vote.update_attributes(params[:song_vote])
        format.html { redirect_to(@song_vote, :notice => 'Song vote was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @song_vote.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /song_votes/1
  # DELETE /song_votes/1.xml
  def destroy
    @song_vote = SongVote.find(params[:id])
    @song_vote.destroy

    respond_to do |format|
      format.html { redirect_to(song_votes_url) }
      format.xml  { head :ok }
    end
  end
  
  def reset
    SongVote.find_each do |sv|
      sv.destroy
    end
    redirect_to all_song_charts_path
  end
end

app/helpers/song_votes_helper.rb
module SongVotesHelper
end

app/views/song_votes/_form.html.erb
<%= form_for(@song_vote) do |f| %>
  <% if @song_vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song_vote.errors.count, "error") %> prohibited this song_vote from being saved:</h2>

      <ul>
      <% @song_vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/song_votes/edit.html.erb
<h1>Editing song_vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @song_vote %> |
<%= link_to 'Back', song_votes_path %>

app/views/song_votes/index.html.erb
<h1>Listing song_votes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @song_votes.each do |song_vote| %>
  <tr>
    <td><%= link_to 'Show', song_vote %></td>
    <td><%= link_to 'Edit', edit_song_vote_path(song_vote) %></td>
    <td><%= link_to 'Destroy', song_vote, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song vote', new_song_vote_path %>

app/views/song_votes/new.html.erb
<h1>New song_vote</h1>

<%= render 'form' %>

<%= link_to 'Back', song_votes_path %>

app/views/song_votes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_song_vote_path(@song_vote) %> |
<%= link_to 'Back', song_votes_path %>