config/routes.rb
Crossingmusic::Application.routes.draw do |map|
  match "/album/:album_id/delete_song/:id" => "songs#destroy",:as=>:delete_song
  resources :albums do
    resources :songs
  end
  

  resources :users,:all_song_charts,:contact_messages
  
  resources :user_sessions

  match "/", :to => "albums#index"
  match "/about", :to => "main#about"
  match "/contact", :to => "main#contact",:as=>:contact_us
  match "login" => "user_sessions#new",:as=>:login
  match "logout" => "user_sessions#destroy",:as=>:logout
  match "/song_votes/reset" => "song_votes#reset",:as=>:reset_votes

  match ':controller(/:action(/:id(.:format)))'
end

app/models/song.rb
require 'paperclip'
class Song < ActiveRecord::Base
  belongs_to :album
  has_many :song_votes
  has_attached_file :recording,
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/amazon_s3.yml",
                    :path => ":attachment/:id/:style/:basename.:extension",
                    :s3_host_alias => "mp3.crossingsongs.com",
                    :url=>":s3_alias_url",
                    :bucket=>"mp3.crossingsongs.com"
  
  scope :deleted,where("songs.deleted_at is not null")
  scope :active,where("songs.deleted_at is null")
  scope :ordered,active.order("placement ASC")
                    
  def next
    Song.ordered.where("placement > #{self.placement}").limit(1).first
  end 
  
  def destroy
    update_attributes!(:deleted_at=>DateTime.now)
  end      
  
  def to_chart_json
    "{name: '#{self.name}',data: [#{song_votes.positive.size}, #{song_votes.neutral.size}, #{song_votes.negative.size}]}"
  end  
  
  #class methods
  def self.update_order!(new_order)
    transaction { new_order.each_with_index{|id,idx| update(id.to_i, :placement => idx.to_i)} }
  end      
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter do
    @tab = "SONGS"
  end

  def index
    @album = Album.find(params[:album_id])
    @songs = @album.songs.active
  end

  def new
    @album = Album.find(params[:album_id])
    @song = Song.new
  end

  def edit
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])
  end

  def create
    @album = Album.find(params[:album_id])
    @song = Song.new(params[:song].merge({:album_id=>@album.id}))

    if @song.save
      redirect_to album_songs_path(@album)
    else
      render :action => "new"
    end
  end

  def update
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])
    if @song.update_attributes(params[:song])
      redirect_to album_songs_path(@album)
    else  
      render :action => "edit"
    end
  end

  def destroy
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to album_songs_path(@album)
  end
  
  def reorder
    @songs = Song.ordered.all
  end
  
  def update_order
    Song.update_order!(params[:order])
    head :ordered
  end
  
  def show
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.haml
=form_for [album,song], :html=>{:multipart => true} do |f|
  %fieldset.song
    =f.label :name,"Name:"
    =f.text_field :name
    %br
    =f.label :recording,"recording"
    =f.file_field :recording
  =f.submit "Save"

app/views/songs/_playlist.html.haml
.side_box
  .title
    %div{:style=>"float:left; width:100px;"} VOTE HERE
    .icon
      %img{:src=>"/images/icon_eighth_note.gif",:alt=>"twitter",:width=>"26",:height=>"26"}
  -@songs.each do |song|
    .song=link_to song.name,song
  -if false #current_user
    %hr
    =link_to "Re-Order Songs",reorder_songs_path
  %hr.clear
.side_box
  %p Click on each song above to listen and vote!  Once you've rated a song, you'll automatically be taken to the next recording in the list. We’ll take the results and go to a real studio to record your favorite five or six tracks.

app/views/songs/edit.html.haml
.left
  %h1= "Edit Song for '#{@album.name}'"
  =render :partial=>"form",:locals=>{:album=>@album,:song=>@song}

app/views/songs/index.html.haml
.left
  %h1= "Songs for '#{@album.name}'"
  %ul#song_list
    -@songs.each_with_index do |song,idx|
      %li.song
        = "#{idx + 1}) #{song.name}"
        =link_to "Edit",edit_album_song_path(@album,song)
        =link_to "Remove",delete_song_path(:album_id=>@album.id,:id=>song.id)
  =link_to "Add a Song",new_album_song_path(@album)

app/views/songs/new.html.haml
.left
  %h1= "New Song for '#{@album.name}'"
  =render :partial=>"form",:locals=>{:album=>@album,:song=>@song}

app/views/songs/reorder.html.haml
:javascript
  $(function() {
    $("#sortable").sortable({
      update: function(event, ui) {
        var result = $("#sortable").sortable("toArray");
        $.post('/songs/update_order',{order: result});
      }
    });
  	$("#sortable").disableSelection();
  });
-if false#current_user
  %ul#sortable
    -@songs.each do |song|
      %li.ui-state-default{:id=>song.id}
        %span.ui-icon.ui-icon-arrowthick-2-n-s
        = song.name

app/views/songs/show.html.haml
.left
  .song_player
    #title{:data_id=>@song.id}= @song.name
    #mp3_widget
      = raw(google_mp3_player @song.recording.url)
  %br
  %br
  =link_to "Back to Album",albums_path