config/routes.rb
Crossingmusic::Application.routes.draw do |map|
  match "/album/:album_id/delete_song/:id" => "songs#destroy",:as=>:delete_song
  resources :albums do
    resources :songs
  end
  

  resources :users,:all_song_charts,:contact_messages
  
  resources :user_sessions

  match "/", :to => "albums#index"
  match "/about", :to => "main#about"
  match "/contact", :to => "main#contact",:as=>:contact_us
  match "login" => "user_sessions#new",:as=>:login
  match "logout" => "user_sessions#destroy",:as=>:logout
  match "/song_votes/reset" => "song_votes#reset",:as=>:reset_votes

  match ':controller(/:action(/:id(.:format)))'
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :songs

  has_attached_file :cover, 
                    :styles => { :thumb => "100x100>"},
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root.to_s}/config/amazon_s3.yml",
                    :s3_permissions => :public_read,
                    :path => ":attachment/:style/:id.:extension"
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate,:except=>[:index]
  
  def index
    @tab = "SONGS"
    @albums = Album.order("created_at DESC").all
  end
  
  def new
    @album = Album.new
  end
  
  def create
    @album = Album.new(params[:album])

    if @album.save
      redirect_to albums_path
    else
      render :action => "new" 
    end
  end
  
  def edit
    @album = Album.find(params[:id])
  end
  
  def update
    @album = Album.find(params[:id])

    if @album.update_attributes(params[:album])
      redirect_to albums_path
    else
      render :action => "edit" 
    end
  end
  
  def show
    @album = Album.find(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_display.html.haml
#album_display
  #album_left
    #album_header
      %h2= album.name
      =link_to album.band_camp_url do
        =image_tag "buy_now.jpeg"
      -if current_user
        =link_to "Edit",edit_album_path(album)
        =link_to "Manage Songs",album_songs_path(album)
    #album_cover
      %img{:src=>album.cover.url}
  #album_songs
    %h3 Track List
    %ul#song_list
    - album.songs.ordered.each_with_index do |song,idx|
      %li.song
        = "#{idx + 1}) #{song.name}"
        =link_to "Listen",album_song_path(album,song)
    %br
    =link_to album.band_camp_url do
      =image_tag "buy_now.jpeg"
  #album_clear

app/views/albums/_form.html.haml
= form_for(album, :html=>{:multipart => true}) do |f|
  =render "shared/error_messages",:target=>album
  .field
    = f.label :name 
    = f.text_field :name 
  .field
    = f.label :cover
    = f.file_field :cover
  .field
    = f.label :band_camp_url
    = f.text_field :band_camp_url
  .actions
    = f.submit 

app/views/albums/edit.html.haml
.left
  %h3= "Editing #{@album.name}"
  =render("form",:album=>@album)
  =link_to "Manage Songs",album_songs_path(@album)
.right

app/views/albums/index.html.haml
.full
  %h1 The Crossing Music Albums
  =render "display",:album=>@albums.first
  #discography
    %h3 Discography
    %ul#albums
      -@albums.each do |album|
        %li.album
          =link_to album do
            =image_tag album.cover.url(:thumb)
          %br
          =link_to album.name,album
          -if current_user
            \--    
            =link_to "edit",edit_album_path(album)
            \--
            =link_to "manage songs",album_songs_path(album)
  #disc_footer
    -if current_user
      =button_to "Add an Album",new_album_path
    %p Listen to and buy the latest projects from The Crossing Music
    #mp3_widget
      = raw(google_mp3_player "http://mp3.crossingsongs.com.s3.amazonaws.com/fixed/Forever_Home_Streaming_Sample.mp3")

app/views/albums/new.html.haml
.left
  %h3 New Album
  =render("form",:album=>@album)
.right

app/views/albums/show.html.haml
=render :partial=>"display",:locals=>{:album=>@album}